# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rohan J Billava\Desktop\myjarvis\jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisUI(object):
    def setupUi(self, jarvisUI):
        jarvisUI.setObjectName("jarvisUI")
        jarvisUI.resize(1249, 862)
        self.centralwidget = QtWidgets.QWidget(jarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1251, 871))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\Rohan J Billava\\Desktop\\myjarvis\\images/7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 720, 91, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(14, 14, 14);\n"
"color: rgb(191, 191, 191);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 720, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(14, 14, 14);\n"
"color: rgb(191, 191, 191);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 471, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\Rohan J Billava\\Desktop\\myjarvis\\images/T8bahf.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(970, 20, 281, 61))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(690, 20, 281, 61))
        self.textBrowser_3.setStyleSheet("background:transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-size:20px;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        jarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvisUI)
        QtCore.QMetaObject.connectSlotsByName(jarvisUI)

    def retranslateUi(self, jarvisUI):
        _translate = QtCore.QCoreApplication.translate
        jarvisUI.setWindowTitle(_translate("jarvisUI", "MainWindow"))
        self.pushButton.setText(_translate("jarvisUI", "START"))
        self.pushButton_2.setText(_translate("jarvisUI", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisUI = QtWidgets.QMainWindow()
    ui = Ui_jarvisUI()
    ui.setupUi(jarvisUI)
    jarvisUI.show()
    sys.exit(app.exec_())
